version: "3"
services:
  bot:
    build: .
    image: woop/memebot:latest
    environment:
      - BOT_TOKEN=SUCH_SECRET_CHANGE_IN_OVERRIDE
      - TZ=Europe/Berlin
    container_name: memebot
    restart: always
    volumes:
      - your_volume:/usr/src/app/bot/neocortex
volumes:
  your_volume: