version: "3"
services:
  bot:
    build: .
    image: woop/memebot:latest
    environment:
      - BOT_TOKEN=SUCH_SECRET_CHANGE_IN_OVERRIDE
      - TZ=Europe/Berlin
    container_name: memebot
    restart: always
