version: "3"
services:
  bot:
    build: .
    image: woop/memebot:latest
    environment:
      # - BOT_TOKEN=SECRET change this in docker-compose override
      - TZ=Europe/London
      # - ADMINS=<admin_id_1>,<admin_id_2> change this in docker-compose override or set it here.
    container_name: memebot
    restart: always
    volumes:
      - your_volume:/usr/src/app/bot/neocortex
volumes:
  your_volume: